name: Unit Tests

on: pull_request
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: 👾 Clone repo to runner
        uses: actions/checkout@v4

      - name: 🐍 Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.26
          python-version: 3.13

      - name: 👀 Check python and uv versions
        run: |
          uv run python --version
          uv --version

      - name: 🚧 Install the project
        run: uv sync --all-extras --dev

      - name: 🚀 Run unit tests
        run: uv run pytest --cov-report=xml

      - name: 📤 Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
